#Praktikum 1
Praktikum 1 ini akan membuat JST sederhana (2 layer) dengan forward pass dan backpropagation manual.

Backpropagation adalah sebuah algoritma untuk melatih jaringan saraf tiruan dengan cara mengoreksi kesalahan. Algoritma ini bekerja dengan cara menghitung selisih antara keluaran yang dihasilkan jaringan dan keluaran yang seharusnya (kesalahan), lalu memperbarui bobot dan bias jaringan secara berulang dari keluaran ke masukan untuk meminimalkan kesalahan tersebut. Cara kerja backpropagation

- Perambatan maju (forward pass): Data masukan diproses melalui jaringan dari lapisan masukan ke lapisan keluaran untuk menghasilkan prediksi awal.

- Hitung kesalahan: Selisih antara keluaran prediksi dan keluaran target dihitung menggunakan fungsi kerugian.

- Perambatan mundur (backward pass): Kesalahan disebarkan kembali ke belakang melalui jaringan dari lapisan keluaran ke lapisan masukan untuk menghitung gradien atau turunan parsial dari fungsi kerugian terhadap bobot dan bias.

- Perbarui bobot: Bobot dan bias disesuaikan menggunakan algoritma penurunan gradien untuk mengurangi kesalahan pada iterasi berikutnya. <br>

Langkah:
1. Buat dataset sederhana (XOR).
2. Inisialisasi bobot dan bias.
3. Implementasikan forward pass.
4. Hitung error dan lakukan backpropagation.
5. Update bobot menggunakan gradient descent.

In [3]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.2708653390982532
Epoch 1000, Loss: 0.24700221798634414
Epoch 2000, Loss: 0.22163637175728887
Epoch 3000, Loss: 0.16733408856600135
Epoch 4000, Loss: 0.14360069722552177
Epoch 5000, Loss: 0.13564503632839234
Epoch 6000, Loss: 0.13220685240769198
Epoch 7000, Loss: 0.1303724998450319
Epoch 8000, Loss: 0.1292525928057126
Epoch 9000, Loss: 0.12850473083219477
Prediksi:
[[0.05438475]
 [0.95680334]
 [0.49469552]
 [0.50173377]]


# Tugas


## 1. Ubah jumlah neuron hidden layer menjadi 3.

In [4]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
y = np.array([[0],
              [1],
              [1],
              [0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1
np.random.seed(42)

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):

    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    error = y - a2

    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss:.6f}")

# Output
print("\nPrediksi akhir (hidden_size = 3, sigmoid):")
print(a2)
final_loss = np.mean(np.square(y - a2))
print("Final Loss:", final_loss)


Epoch 0, Loss: 0.318245
Epoch 1000, Loss: 0.205697
Epoch 2000, Loss: 0.141854
Epoch 3000, Loss: 0.058651
Epoch 4000, Loss: 0.020112
Epoch 5000, Loss: 0.009992
Epoch 6000, Loss: 0.006270
Epoch 7000, Loss: 0.004461
Epoch 8000, Loss: 0.003421
Epoch 9000, Loss: 0.002756

Prediksi akhir (hidden_size = 3, sigmoid):
[[0.02515564]
 [0.95263635]
 [0.95122343]
 [0.0627247 ]]
Final Loss: 0.0022974157268842183


## 2. Bandingkan hasil loss dengan konfigurasi awal.

> Pada arsitektur dengan 2 neuron hidden, jaringan masih kesulitan memisahkan semua pola XOR sehingga final loss berhenti sekitar 0,128 dan beberapa output mendekati 0,5. Setelah jumlah neuron hidden ditambah menjadi 3, jaringan memiliki kapasitas representasi yang lebih besar sehingga mampu mempelajari fungsi XOR dengan lebih baik, ditunjukkan oleh penurunan final loss hingga sekitar 0,0023 dan output yang mendekati nilai target (0 atau 1) pada seluruh kombinasi input

3.
Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.

In [5]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1
epochs = 10000

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    # x di sini adalah output sigmoid (a)
    return x * (1 - x)

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    # x di sini adalah z (pre-activation)
    return (x > 0).astype(float)

# ==============================
# 1) MODEL DENGAN HIDDEN SIGMOID
# ==============================
np.random.seed(42)  # supaya adil, inisialisasi sama

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

print("=== TRAINING MODEL HIDDEN SIGMOID ===")
for epoch in range(epochs):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)          # hidden pakai sigmoid
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)          # output pakai sigmoid

    # Hitung error
    error = y - a2
    loss = np.mean(np.square(error))

    # Print loss tiap 1000 epoch
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss (sigmoid hidden): {loss:.6f}")

    # Backprop
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

# Simpan hasil sigmoid
pred_sigmoid = a2
loss_sigmoid = np.mean(np.square(y - pred_sigmoid))

print("\n=== HASIL AKHIR MODEL HIDDEN SIGMOID ===")
print("Prediksi (sigmoid hidden):")
print(pred_sigmoid)
print("Final Loss (sigmoid hidden):", loss_sigmoid)
print("\n")


# ===========================
# 2) MODEL DENGAN HIDDEN ReLU
# ===========================
np.random.seed(42)  # reset seed supaya bobot awal sama

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

print("=== TRAINING MODEL HIDDEN ReLU ===")
for epoch in range(epochs):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)             # hidden pakai ReLU
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)          # output tetap sigmoid

    # Hitung error
    error = y - a2
    loss = np.mean(np.square(error))

    # Print loss tiap 1000 epoch
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss (ReLU hidden): {loss:.6f}")

    # Backprop
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

# Simpan hasil ReLU
pred_relu = a2
loss_relu = np.mean(np.square(y - pred_relu))

print("\n=== HASIL AKHIR MODEL HIDDEN ReLU ===")
print("Prediksi (ReLU hidden):")
print(pred_relu)
print("Final Loss (ReLU hidden):", loss_relu)


=== TRAINING MODEL HIDDEN SIGMOID ===
Epoch 0, Loss (sigmoid hidden): 0.255830
Epoch 1000, Loss (sigmoid hidden): 0.249406
Epoch 2000, Loss (sigmoid hidden): 0.245445
Epoch 3000, Loss (sigmoid hidden): 0.204707
Epoch 4000, Loss (sigmoid hidden): 0.153204
Epoch 5000, Loss (sigmoid hidden): 0.138691
Epoch 6000, Loss (sigmoid hidden): 0.133594
Epoch 7000, Loss (sigmoid hidden): 0.131151
Epoch 8000, Loss (sigmoid hidden): 0.129749
Epoch 9000, Loss (sigmoid hidden): 0.128849

=== HASIL AKHIR MODEL HIDDEN SIGMOID ===
Prediksi (sigmoid hidden):
[[0.05300868]
 [0.49554213]
 [0.95091319]
 [0.50319888]]
Final Loss (sigmoid hidden): 0.1282265715241046


=== TRAINING MODEL HIDDEN ReLU ===
Epoch 0, Loss (ReLU hidden): 0.261648
Epoch 1000, Loss (ReLU hidden): 0.126387
Epoch 2000, Loss (ReLU hidden): 0.125405
Epoch 3000, Loss (ReLU hidden): 0.125227
Epoch 4000, Loss (ReLU hidden): 0.125163
Epoch 5000, Loss (ReLU hidden): 0.125116
Epoch 6000, Loss (ReLU hidden): 0.125096
Epoch 7000, Loss (ReLU hidden)

> Dengan 2 neuron hidden, baik aktivasi sigmoid maupun ReLU sama-sama belum mampu mempelajari pola XOR secara sempurna (masih ada dua kombinasi input yang diprediksi mendekati 0,5). Namun, model dengan aktivasi ReLU menghasilkan nilai loss sedikit lebih kecil (0,1250) dibanding sigmoid (0,1282), karena pada beberapa input seperti [0,1] dan [1,1] prediksinya sangat dekat dengan nilai target. Hal ini menunjukkan bahwa pemilihan fungsi aktivasi dapat memengaruhi seberapa baik jaringan belajar, meskipun dengan arsitektur kecil seperti ini perbedaannya belum terlalu signifikan.